#!/usr/bin/python3
import os

pyfile = os.environ.get('PYFILE')
if pyfile is None:
    print("PYFILE environment variable not set")
    exit(1)

pycfile = pyfile + 'c'
try:
    with open(pyfile, 'rb') as f:
        code = compile(f.read(), pyfile, 'exec')
    with open(pycfile, 'wb') as f:
        f.write(code)
except IOError as e:
    print(e)
    exit(1)

print(f"Compiled {pyfile} to {pycfile}")
